
DROP TABLE PROFILE.T_ROLE;

DROP TABLE PROFILE.T_PHONE_NUMBER;

DROP TABLE PROFILE.T_USER_ADDRESS;

DROP TABLE PROFILE.T_IDENTITY_DOCUMENT;

DROP TABLE PROFILE.T_MEDIA_FILE;

DROP TABLE PROFILE.T_USER;