CREATE TABLE PROFILE.T_MEDIA_FILE
(
	ID BINARY(16) NOT NULL,	
	FILE_NAME VARCHAR(255) NOT NULL,
	FILE_TYPE VARCHAR(255) NOT NULL,
	FILE_DATA MEDIUMBLOB NOT NULL
);

ALTER TABLE PROFILE.T_MEDIA_FILE ADD PRIMARY KEY (ID);