-- create user table
CREATE TABLE PROFILE.T_USER
(
	ID BINARY(16) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	FIRST_NAME VARCHAR(255) NOT NULL,
	MIDDLE_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	DOB DATE NOT NULL,
	NATIONALITY SMALLINT NOT NULL,
	CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE PROFILE.T_USER ADD PRIMARY KEY (ID);

ALTER TABLE PROFILE.T_USER ADD CONSTRAINT NK_UNIQUE_EMAIL UNIQUE (EMAIL);

ALTER TABLE PROFILE.T_USER ADD CONSTRAINT FK_NATIONALITY 
FOREIGN KEY (NATIONALITY) REFERENCES LOOKUP.T_COUNTRY(ID);