ALTER TABLE PROFILE.T_USER CHANGE FIRST_NAME FIRST_NAME VARCHAR(255) DEFAULT NULL;
ALTER TABLE PROFILE.T_USER CHANGE DOB DOB DATE DEFAULT NULL;
ALTER TABLE PROFILE.T_USER CHANGE NATIONALITY NATIONALITY smallint(6) DEFAULT NULL;