CREATE TABLE PROFILE.T_PHONE_NUMBER
(
	ID BINARY(16) NOT NULL,
	FK_USER_ID BINARY(16) NOT NULL,
	FK_PHONE_TYPE_CD SMALLINT NOT NULL,
	FK_COUNTRY_CD SMALLINT NOT NULL,
	NUMBER VARCHAR(15) NOT NULL
);

ALTER TABLE PROFILE.T_PHONE_NUMBER ADD PRIMARY KEY (ID);

ALTER TABLE PROFILE.T_PHONE_NUMBER ADD CONSTRAINT ONLY_ONE_PHONE_PER_TYPE UNIQUE (FK_USER_ID, FK_PHONE_TYPE_CD);

ALTER TABLE PROFILE.T_PHONE_NUMBER ADD CONSTRAINT FK_PHONE_TO_USER 
FOREIGN KEY (FK_USER_ID) REFERENCES PROFILE.T_USER(ID);

ALTER TABLE PROFILE.T_PHONE_NUMBER ADD CONSTRAINT FK_PHONE_TO_TYPE 
FOREIGN KEY (FK_PHONE_TYPE_CD) REFERENCES LOOKUP.T_PHONE_TYPE(CD);

ALTER TABLE PROFILE.T_PHONE_NUMBER ADD CONSTRAINT FK_PHONE_TO_COUNTRY 
FOREIGN KEY (FK_COUNTRY_CD) REFERENCES LOOKUP.T_COUNTRY(CD);