CREATE TABLE PROFILE.T_USER_ADDRESS
(
	ID BINARY(16) NOT NULL,
	FK_USER_ID BINARY(16) NOT NULL,
	HOUSE_NO SMALLINT(255) NOT NULL,
	STREET VARCHAR(255) NOT NULL,
	CITY VARCHAR(255) NOT NULL,
	ZIP VARCHAR(50) NOT NULL,
	STATE VARCHAR(255) NOT NULL,
	FK_COUNTRY_CD SMALLINT NOT NULL
);

ALTER TABLE PROFILE.T_USER_ADDRESS ADD PRIMARY KEY (ID);

ALTER TABLE PROFILE.T_USER_ADDRESS ADD CONSTRAINT ONLY_ONE_PER_USER UNIQUE (FK_USER_ID);

ALTER TABLE PROFILE.T_USER_ADDRESS ADD CONSTRAINT FK_ADDR_TO_USER 
FOREIGN KEY (FK_USER_ID) REFERENCES PROFILE.T_USER(ID);

ALTER TABLE PROFILE.T_USER_ADDRESS ADD CONSTRAINT FK_ADDR_TO_COUNTRY 
FOREIGN KEY (FK_COUNTRY_CD) REFERENCES LOOKUP.T_COUNTRY(CD);