INSERT INTO LOOKUP.T_PHONE_TYPE (CD, DESCRIPTION) VALUES (1, "Mobile");

INSERT INTO LOOKUP.T_PHONE_TYPE (CD, DESCRIPTION) VALUES (2, "Home");

INSERT INTO LOOKUP.T_PHONE_TYPE (CD, DESCRIPTION) VALUES (3, "Office");