INSERT INTO LOOKUP.T_CURRENCY VALUES 
(1,'AF','AFG','AFN','Afghan afghani','؋'),
(3,'AL','ALB','ALL','Albanian lek','L'),
(4,'DZ','DZA','DZD','Algerian dinar','د.ج'),
(5,'AS','ASM','','',''),
(6,'AD','AND','EUR','Euro','€'),
(7,'AO','AGO','AOA','Angolan kwanza','Kz'),
(8,'AI','AIA','XCD','East Caribbean dolla','$'),
(10,'AG','ATG','XCD','East Caribbean dolla','$'),
(11,'AR','ARG','ARS','Argentine peso','$'),
(12,'AM','ARM','AMD','Armenian dram',''),
(13,'AW','ABW','AWG','Aruban florin','ƒ'),
(14,'AU','AUS','AUD','Australian dollar','$'),
(15,'AT','AUT','EUR','Euro','€'),
(16,'AZ','AZE','AZN','Azerbaijani manat',''),
(17,'BS','BHS','','',''),
(18,'BH','BHR','BHD','Bahraini dinar','.د.ب'),
(19,'BD','BGD','BDT','Bangladeshi taka','৳'),
(20,'BB','BRB','BBD','Barbadian dollar','$'),
(21,'BY','BLR','BYR','Belarusian ruble','Br'),
(22,'BE','BEL','EUR','Euro','€'),
(23,'BZ','BLZ','BZD','Belize dollar','$'),
(24,'BJ','BEN','XOF','West African CFA fra','Fr'),
(25,'BM','BMU','BMD','Bermudian dollar','$'),
(26,'BT','BTN','BTN','Bhutanese ngultrum','Nu.'),
(27,'BO','BOL','','',''),
(28,'BA','BIH','','',''),
(29,'BW','BWA','BWP','Botswana pula','P'),
(30,'BR','BRA','BRL','Brazilian real','R$'),
(32,'BN','BRN','','',''),
(33,'BG','BGR','BGN','Bulgarian lev','лв'),
(34,'BF','BFA','XOF','West African CFA fra','Fr'),
(35,'BI','BDI','BIF','Burundian franc','Fr'),
(36,'KH','KHM','KHR','Cambodian riel','៛'),
(37,'CM','CMR','XAF','Central African CFA ','Fr'),
(38,'CA','CAN','CAD','Canadian dollar','$'),
(39,'CV','CPV','CVE','Cape Verdean escudo','Esc or $'),
(40,'KY','CYM','KYD','Cayman Islands dolla','$'),
(41,'CF','CAF','','',''),
(42,'TD','TCD','XAF','Central African CFA ','Fr'),
(43,'CL','CHL','CLP','Chilean peso','$'),
(44,'CN','CHN','CNY','Chinese yuan','¥ or 元'),
(47,'CO','COL','COP','Colombian peso','$'),
(48,'KM','COM','KMF','Comorian franc','Fr'),
(49,'CG','COG','','',''),
(51,'CK','COK','NZD','New Zealand dollar','$'),
(52,'CR','CRI','CRC','Costa Rican colón','₡'),
(53,'CI','CIV','XOF','West African CFA fra','Fr'),
(54,'HR','HRV','HRK','Croatian kuna','kn'),
(55,'CU','CUB','CUC','Cuban convertible pe','$'),
(56,'CY','CYP','EUR','Euro','€'),
(57,'CZ','CZE','CZK','Czech koruna','Kč'),
(58,'DK','DNK','DKK','Danish krone','kr'),
(59,'DJ','DJI','DJF','Djiboutian franc','Fr'),
(60,'DM','DMA','XCD','East Caribbean dolla','$'),
(61,'DO','DOM','DOP','Dominican peso','$'),
(62,'EC','ECU','USD','United States dollar','$'),
(63,'EG','EGY','EGP','Egyptian pound','£ or ج.م'),
(64,'SV','SLV','USD','United States dollar','$'),
(65,'GQ','GNQ','XAF','Central African CFA ','Fr'),
(66,'ER','ERI','ERN','Eritrean nakfa','Nfk'),
(67,'EE','EST','EUR','Euro','€'),
(68,'ET','ETH','ETB','Ethiopian birr','Br'),
(69,'FK','FLK','','',''),
(70,'FO','FRO','DKK','Danish krone','kr'),
(71,'FJ','FJI','FJD','Fijian dollar','$'),
(72,'FI','FIN','EUR','Euro','€'),
(73,'FR','FRA','EUR','Euro','€'),
(74,'GF','GUF','','',''),
(75,'PF','PYF','XPF','CFP franc','Fr'),
(76,'GA','GAB','XAF','Central African CFA ','Fr'),
(77,'GM','GMB','','',''),
(78,'GE','GEO','GEL','Georgian lari','ლ'),
(79,'DE','DEU','EUR','Euro','€'),
(80,'GH','GHA','GHS','Ghana cedi','₵'),
(81,'GI','GIB','GIP','Gibraltar pound','£'),
(82,'GR','GRC','EUR','Euro','€'),
(83,'GL','GRL','','',''),
(84,'GD','GRD','XCD','East Caribbean dolla','$'),
(85,'GP','GLP','','',''),
(86,'GU','GUM','','',''),
(87,'GT','GTM','GTQ','Guatemalan quetzal','Q'),
(89,'GN','GIN','GNF','Guinean franc','Fr'),
(90,'GW','GNB','XOF','West African CFA fra','Fr'),
(91,'GY','GUY','GYD','Guyanese dollar','$'),
(92,'HT','HTI','HTG','Haitian gourde','G'),
(93,'VA','VAT','','',''),
(94,'HN','HND','HNL','Honduran lempira','L'),
(95,'HK','HKG','HKD','Hong Kong dollar','$'),
(96,'HU','HUN','HUF','Hungarian forint','Ft'),
(97,'IS','ISL','ISK','Icelandic króna','kr'),
(98,'IN','IND','INR','Indian rupee','₹'),
(99,'ID','IDN','IDR','Indonesian rupiah','Rp'),
(100,'IR','IRN','','',''),
(101,'IQ','IRQ','IQD','Iraqi dinar','ع.د'),
(102,'IE','IRL','EUR','Euro','€'),
(104,'IL','ISR','ILS','Israeli new shekel','₪'),
(105,'IT','ITA','EUR','Euro','€'),
(106,'JM','JAM','JMD','Jamaican dollar','$'),
(107,'JP','JPN','JPY','Japanese yen','¥'),
(109,'JO','JOR','JOD','Jordanian dinar','د.ا'),
(110,'KZ','KAZ','KZT','Kazakhstani tenge',''),
(111,'KE','KEN','KES','Kenyan shilling','Sh'),
(112,'KI','KIR','AUD','Australian dollar','$'),
(113,'KP','PRK','','',''),(114,'KR','KOR','','',''),
(115,'KW','KWT','KWD','Kuwaiti dinar','د.ك'),
(116,'KG','KGZ','KGS','Kyrgyzstani som','лв'),
(117,'LA','LAO','LAK','Lao kip','₭'),
(118,'LV','LVA','EUR','Euro','€'),
(119,'LB','LBN','LBP','Lebanese pound','ل.ل'),
(120,'LS','LSO','LSL','Lesotho loti','L'),
(121,'LR','LBR','LRD','Liberian dollar','$'),
(122,'LY','LBY','','',''),
(123,'LI','LIE','CHF','Swiss franc','Fr'),
(124,'LT','LTU','EUR','Euro','€'),
(125,'LU','LUX','EUR','Euro','€'),
(126,'MO','MAC','','',''),
(127,'MK','MKD','','',''),
(128,'MG','MDG','MGA','Malagasy ariary','Ar'),
(129,'MW','MWI','MWK','Malawian kwacha','MK'),
(130,'MY','MYS','MYR','Malaysian ringgit','RM'),
(131,'MV','MDV','MVR','Maldivian rufiyaa','.ރ'),
(132,'ML','MLI','XOF','West African CFA fra','Fr'),
(133,'MT','MLT','EUR','Euro','€'),
(134,'MH','MHL','USD','United States dollar','$'),
(135,'MQ','MTQ','','',''),
(136,'MR','MRT','MRO','Mauritanian ouguiya','UM'),
(137,'MU','MUS','MUR','Mauritian rupee','₨'),
(139,'MX','MEX','MXN','Mexican peso','$'),
(140,'FM','FSM','','',''),(141,'MD','MDA','MDL','Moldovan leu','L'),
(142,'MC','MCO','EUR','Euro','€'),
(143,'MN','MNG','MNT','Mongolian tögrög','₮'),
(145,'MS','MSR','XCD','East Caribbean dolla','$'),
(146,'MA','MAR','MAD','Moroccan dirham','د.م.'),
(147,'MZ','MOZ','MZN','Mozambican metical','MT'),
(148,'MM','MMR','MMK','Burmese kyat','Ks'),
(149,'NA','NAM','NAD','Namibian dollar','$'),
(150,'NR','NRU','AUD','Australian dollar','$'),
(151,'NP','NPL','NPR','Nepalese rupee','₨'),
(152,'NL','NLD','EUR','Euro','€'),
(153,'AN','ANT','','',''),
(154,'NC','NCL','XPF','CFP franc','Fr'),
(155,'NZ','NZL','NZD','New Zealand dollar','$'),
(156,'NI','NIC','NIO','Nicaraguan córdoba','C$'),
(157,'NE','NER','XOF','West African CFA fra','Fr'),
(158,'NG','NGA','NGN','Nigerian naira','₦'),
(159,'NU','NIU','NZD','New Zealand dollar','$'),
(160,'NF','NFK','','',''),
(161,'MP','MNP','','',''),
(162,'NO','NOR','NOK','Norwegian krone','kr'),
(163,'OM','OMN','OMR','Omani rial','ر.ع.'),
(164,'PK','PAK','PKR','Pakistani rupee','₨'),
(165,'PW','PLW','','Palauan dollar','$'),
(167,'PA','PAN','PAB','Panamanian balboa','B/.'),
(168,'PG','PNG','PGK','Papua New Guinean ki','K'),
(169,'PY','PRY','PYG','Paraguayan guaraní','₲'),
(170,'PE','PER','PEN','Peruvian nuevo sol','S/.'),
(171,'PH','PHL','PHP','Philippine peso','₱'),
(172,'PN','PCN','','',''),
(173,'PL','POL','PLN','Polish z?oty','zł'),
(174,'PT','PRT','EUR','Euro','€'),
(175,'PR','PRI','','',''),
(176,'QA','QAT','QAR','Qatari riyal','ر.ق'),
(177,'RO','ROM','RON','Romanian leu','lei'),
(178,'RU','RUS','RUB','Russian ruble',''),
(179,'RW','RWA','RWF','Rwandan franc','Fr'),
(180,'RE','REU','','',''),
(182,'SH','SHN','','',''),
(183,'KN','KNA','','',''),
(184,'LC','LCA','XCD','East Caribbean dolla','$'),
(186,'PM','SPM','','',''),
(187,'VC','VCT','','',''),
(188,'WS','WSM','WST','Samoan t?l?','T'),
(189,'SM','SMR','EUR','Euro','€'),
(190,'ST','STP','','',''),
(191,'SA','SAU','SAR','Saudi riyal','ر.س'),
(192,'SN','SEN','XOF','West African CFA fra','Fr'),
(194,'SC','SYC','SCR','Seychellois rupee','₨'),
(195,'SL','SLE','SLL','Sierra Leonean leone','Le'),
(196,'SG','SGP','SGD','Singapore dollar','$'),
(197,'SK','SVK','EUR','Euro','€'),
(198,'SI','SVN','EUR','Euro','€'),
(199,'SB','SLB','SBD','Solomon Islands doll','$'),
(200,'SO','SOM','SOS','Somali shilling','Sh'),
(201,'ZA','ZAF','ZAR','South African rand','R'),
(203,'ES','ESP','EUR','Euro','€'),
(204,'LK','LKA','LKR','Sri Lankan rupee','Rs or රු'),
(205,'SD','SDN','SDG','Sudanese pound','ج.س.'),
(206,'SR','SUR','SRD','Surinamese dollar','$'),
(207,'SJ','SJM','','',''),
(208,'SZ','SWZ','SZL','Swazi lilangeni','L'),
(209,'SE','SWE','SEK','Swedish krona','kr'),
(210,'CH','CHE','CHF','Swiss franc','Fr'),
(211,'SY','SYR','','',''),
(212,'TW','TWN','TWD','New Taiwan dollar','$'),
(213,'TJ','TJK','TJS','Tajikistani somoni','ЅМ'),
(214,'TZ','TZA','','',''),
(215,'TH','THA','THB','Thai baht','฿'),
(217,'TG','TGO','XOF','West African CFA fra','Fr'),
(218,'TK','TKL','','',''),
(219,'TO','TON','TOP','Tongan pa?anga','T$'),
(220,'TT','TTO','TTD','Trinidad and Tobago ','$'),
(221,'TN','TUN','TND','Tunisian dinar','د.ت'),
(222,'TR','TUR','TRY','Turkish lira',''),
(223,'TM','TKM','TMT','Turkmenistan manat','m'),
(224,'TC','TCA','','',''),
(225,'TV','TUV','AUD','Australian dollar','$'),
(226,'UG','UGA','UGX','Ugandan shilling','Sh'),
(227,'UA','UKR','UAH','Ukrainian hryvnia','₴'),
(228,'AE','ARE','AED','United Arab Emirates','د.إ'),
(229,'GB','GBR','GBP','British pound','£'),
(230,'US','USA','USD','United States dollar','$'),
(231,'UY','URY','UYU','Uruguayan peso','$'),
(232,'UZ','UZB','UZS','Uzbekistani som',''),
(233,'VU','VUT','VUV','Vanuatu vatu','Vt'),
(234,'VE','VEN','','',''),
(235,'VN','VNM','VND','Vietnamese ??ng','₫'),
(236,'VG','VGB','','',''),
(237,'VI','VIR','','',''),
(238,'WF','WLF','XPF','CFP franc','Fr'),
(239,'YE','YEM','YER','Yemeni rial','﷼'),
(240,'ZM','ZMB','ZMW','Zambian kwacha','ZK'),
(241,'ZW','ZWE','BWP','Botswana pula','P');