DROP TABLE IF EXISTS LENDER.T_LENDER_PHONE;
CREATE TABLE LENDER.T_LENDER_PHONE
(
	ID INT primary key,
	FK_LENDER_EXT_REF VARCHAR(32) UNIQUE NOT NULL,
	FK_PHONE_TYPE_CD SMALLINT NOT NULL,
	FK_COUNTRY_ID SMALLINT NOT NULL,
	NUMBER VARCHAR(15) NOT NULL,
    CONSTRAINT FK_PHONE_TO_COUNTRY1 FOREIGN KEY (FK_COUNTRY_ID) REFERENCES LOOKUP.T_COUNTRY(ID)
);
