DROP TABLE IF EXISTS LENDER.T_LENDING_COMPANY;
CREATE TABLE IF NOT exists LENDER.T_LENDING_COMPANY (
	INTERNAL_ID int primary key auto_increment ,
    EXTERNAL_REF VARCHAR(32) unique default (uuid_short()),
	LENDER_NAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    LENDER_TYPE_CODE VARCHAR(8) NOT NULL,
    LENDER_COUNTRY_CODE VARCHAR(2) NOT NULL,
    LENDER_TURNOVER_CCY VARCHAR(3) not null COMMENT 'iso3 code or OTH for crypto',
    LENDER_TURNOVER_MIN INT(10) COMMENT 'Turnover range',
    LENDER_TURNOVER_MAX INT(10) COMMENT 'Turnover range',
    LENDER_WEBSITE_URL VARCHAR(100) NOT NULL,
    LENDER_YEAR_INC SMALLINT COMMENT 'Year incorporated',
    LENDING_CURRENCY_TYPE ENUM('CRYPTO','REGULAR','BOTH')  COMMENT 'CRYPTO or REGULAR CURRENCY or BOTH', 
	CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LENDER_TYPE FOREIGN KEY (LENDER_TYPE_CODE) REFERENCES LOOKUP.T_LENDER_TYPE(LENDER_TYPE_CODE),
    CONSTRAINT FK_LENDER_COUNTRY FOREIGN KEY (LENDER_COUNTRY_CODE) REFERENCES LOOKUP.T_COUNTRY(COUNTRY_CODE_ISO2)
--    CONSTRAINT CK_L_CURRENCY_TYPE CHECK (LENDING_CURRENCY_TYPE IN ('CRYPTO','REGULAR','BOTH'))
);