DROP TABLE IF EXISTS LENDER.T_LENDING_COMPANY_ADDRESS;
CREATE TABLE LENDER.T_LENDING_COMPANY_ADDRESS
(
	ID INT primary key,
	FK_LENDER_EXT_REF VARCHAR(32) UNIQUE NOT NULL,
	HOUSE_NO SMALLINT(255) NOT NULL,
	STREET VARCHAR(255) NOT NULL,
	CITY VARCHAR(255) NOT NULL,
	ZIP VARCHAR(50) NOT NULL,
	STATE VARCHAR(255) NOT NULL,
	FK_COUNTRY_NAME varchar(20) NOT NULL,
    CONSTRAINT FK_LENDER_ID FOREIGN KEY  (FK_LENDER_EXT_REF) REFERENCES T_LENDING_COMPANY (EXTERNAL_REF),
    CONSTRAINT  FK_COUNTRY FOREIGN KEY FK_COUNTRY_NAME (FK_COUNTRY_NAME) REFERENCES LOOKUP.T_COUNTRY (COUNTRY_NAME)
);