CREATE USER Sumeet IDENTIFIED BY 'Yoda2019' REQUIRE SSL;
GRANT ALL PRIVILEGES ON LOOKUP.* TO 'Sumeet'@'%';
GRANT ALL PRIVILEGES ON PROFILE.* TO 'Sumeet'@'%';
FLUSH PRIVILEGES;

CREATE USER Kishore IDENTIFIED BY 'Yoda2019' REQUIRE SSL;
GRANT ALL PRIVILEGES ON LOOKUP.* TO 'Kishore'@'%';
GRANT ALL PRIVILEGES ON PROFILE.* TO 'Kishore'@'%';
FLUSH PRIVILEGES;

CREATE USER Piyush IDENTIFIED BY 'Yoda2019' REQUIRE SSL;
GRANT ALL PRIVILEGES ON LOOKUP.* TO 'Piyush'@'%';
GRANT ALL PRIVILEGES ON PROFILE.* TO 'Piyush'@'%';
FLUSH PRIVILEGES;