CREATE USER Y_TEC_WS IDENTIFIED BY 'Yoda2019' REQUIRE NONE;
GRANT SELECT, INSERT, UPDATE, DELETE ON LOOKUP.* TO 'Y_TEC_WS'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON PROFILE.* TO 'Y_TEC_WS'@'%';
FLUSH PRIVILEGES;