CREATE TABLE LOOKUP.T_LENDER_TYPE (
ID int primary key auto_increment ,
LENDER_TYPE_CODE VARCHAR(10) UNIQUE,
LENDER_TYPE VARCHAR(15) not null,
LENDER_TYPE_CODE_DESC VARCHAR(50) NOT NULL,
USER_CREATED varchar(20),
CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);