--
-- table `country` 
-- File Name DDL_00003_1_T_APP_COUNTRY.sql
--
DROP table LOOKUP.T_APP_COUNTRY;

CREATE TABLE IF NOT EXISTS LOOKUP.T_APP_COUNTRY (
  ID int(11) NOT NULL AUTO_INCREMENT ,
  ISO_CODE char(2) UNIQUE,
  COUNTRY_NAME varchar(80) UNIQUE,
  COUNTRY_NICENAME varchar(80) UNIQUE,
  ISO3_CODE char(3) UNIQUE,
  NUMCODE smallint(6) DEFAULT NULL,
  INT_DIALING_CODE int(5) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

ALTER TABLE LOOKUP.T_APP_COUNTRY AUTO_INCREMENT = 10001;
